CREATE TABLE IF NOT EXISTS worldsend_chart_stats_by_rating_band (
    worldsend_chart_id INTEGER NOT NULL,
    rating_band_id INTEGER NOT NULL,
    rank_aaal INTEGER NOT NULL DEFAULT 0,
    rank_s INTEGER NOT NULL DEFAULT 0,
    rank_sp INTEGER NOT NULL DEFAULT 0,
    rank_ss INTEGER NOT NULL DEFAULT 0,
    rank_ssp INTEGER NOT NULL DEFAULT 0,
    rank_sss INTEGER NOT NULL DEFAULT 0,
    rank_sssp INTEGER NOT NULL DEFAULT 0,
    rank_max INTEGER NOT NULL DEFAULT 0,
    combo_none INTEGER NOT NULL DEFAULT 0,
    combo_fc INTEGER NOT NULL DEFAULT 0,
    combo_aj INTEGER NOT NULL DEFAULT 0,
    clear_failed INTEGER NOT NULL DEFAULT 0,
    clear_clear INTEGER NOT NULL DEFAULT 0,
    clear_hard INTEGER NOT NULL DEFAULT 0,
    clear_brave INTEGER NOT NULL DEFAULT 0,
    clear_absolute INTEGER NOT NULL DEFAULT 0,
    clear_catastrophy INTEGER NOT NULL DEFAULT 0,
    average_score REAL,
    player_count INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (worldsend_chart_id, rating_band_id),
    FOREIGN KEY (rating_band_id) REFERENCES rating_bands (id)
);
